"""initial migration

Revision ID: a31e6b769de5
Revises:
Create Date: 2026-04-29 07:57:41.953094

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a31e6b769de5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        "idx_categories_active_order",
        "categories",
        ["is_active", "display_order"],
        unique=False,
    )
    op.create_table(
        "complaint_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "review_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "service_area_locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "GOOGLE_PLACES",
                "GEOAPIFY",
                name="servicearealocationprovider",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("provider_place_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address_text", sa.String(length=500), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "provider_place_id",
            name="uq_service_area_locations_provider_place_id",
        ),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("profile_photo_url", sa.String(length=500), nullable=True),
        sa.Column(
            "profile_photo_cloudinary_public_id", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "role",
            sa.Enum("BUYER", "SELLER", "ADMIN", name="userrole", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("is_onboarded", sa.Boolean(), nullable=False),
        sa.Column(
            "onboarding_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "account_status",
            sa.Enum(
                "ACTIVE",
                "SUSPENDED",
                "BANNED",
                name="useraccountstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("suspended_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspension_reason", sa.Text(), nullable=True),
        sa.Column("ban_reason", sa.Text(), nullable=True),
        sa.Column("google_uid", sa.String(length=255), nullable=True),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("google_uid"),
    )
    op.create_table(
        "addresses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address_text", sa.Text(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_one_default_address_per_user",
        "addresses",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "carts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("buyer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "SAVED", "CONVERTED", name="cartstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("checked_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_carts_buyer_status_updated",
        "carts",
        ["buyer_id", "status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "device_registrations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.String(length=100), nullable=False),
        sa.Column("push_token", sa.String(length=500), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_device_reg_user_device",
        "device_registrations",
        ["user_id", "device_id"],
        unique=False,
    )
    op.create_table(
        "email_verification_otps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "location_daily_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("orders_count", sa.Integer(), nullable=False),
        sa.Column("buyers_count", sa.Integer(), nullable=False),
        sa.Column("sellers_count", sa.Integer(), nullable=False),
        sa.Column(
            "avg_order_amount", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["service_area_locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "location_id", "metric_date", name="uq_location_daily_metrics_location_date"
        ),
    )
    op.create_index(
        "idx_location_daily_metrics_date",
        "location_daily_metrics",
        ["metric_date"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "ORDER_STATUS",
                "MESSAGE",
                "SYSTEM",
                "PROMOTIONAL",
                name="notificationtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("action_url", sa.String(length=500), nullable=True),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_dismissed", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notifications_user_created",
        "notifications",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "password_reset_otps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verified_token", sa.String(length=128), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "payout_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=False),
        sa.Column("bank_name", sa.String(length=255), nullable=False),
        sa.Column("account_last4", sa.String(length=4), nullable=False),
        sa.Column("provider_recipient_code", sa.String(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "unique_default_payout_account_per_user",
        "payout_accounts",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "refresh_token_blacklist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("jti", sa.String(length=128), nullable=False),
        sa.Column(
            "token_type",
            sa.Enum("ACCESS", "REFRESH", name="tokentype", native_enum=False),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "blacklisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    op.create_table(
        "saved_payment_methods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("method_type", sa.String(length=50), nullable=False),
        sa.Column("provider_token", sa.String(length=255), nullable=False),
        sa.Column("signature", sa.String(length=100), nullable=False),
        sa.Column("brand", sa.String(length=50), nullable=False),
        sa.Column("last4", sa.String(length=4), nullable=False),
        sa.Column("bank", sa.String(length=100), nullable=False),
        sa.Column("expiry_month", sa.SmallInteger(), nullable=True),
        sa.Column("expiry_year", sa.SmallInteger(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("signature"),
        sa.UniqueConstraint("user_id", "signature", name="unique_signature_per_user"),
    )
    op.create_index(
        "unique_default_payment_method_per_user",
        "saved_payment_methods",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "seller_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("store_name", sa.String(length=255), nullable=False),
        sa.Column("bio", sa.Text(), nullable=False),
        sa.Column("profile_image_url", sa.String(length=500), nullable=True),
        sa.Column(
            "profile_image_cloudinary_public_id", sa.String(length=255), nullable=True
        ),
        sa.Column("banner_image_url", sa.String(length=500), nullable=True),
        sa.Column(
            "banner_image_cloudinary_public_id", sa.String(length=255), nullable=True
        ),
        sa.Column("is_accepting_orders", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("avg_rating", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("completed_orders_count", sa.Integer(), nullable=False),
        sa.Column("active_orders_count", sa.Integer(), nullable=False),
        sa.Column("total_items_count", sa.Integer(), nullable=False),
        sa.Column("items_on_sale_count", sa.Integer(), nullable=False),
        sa.Column("weekly_store_views", sa.Integer(), nullable=False),
        sa.Column("average_delivery_minutes", sa.Integer(), nullable=False),
        sa.Column("success_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_blocks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("blocker_user_id", sa.Uuid(), nullable=False),
        sa.Column("blocked_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["blocked_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["blocker_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "blocker_user_id", "blocked_user_id", name="uq_user_blocks_blocker_blocked"
        ),
    )
    op.create_index(
        "idx_user_blocks_blocker", "user_blocks", ["blocker_user_id"], unique=False
    )
    op.create_table(
        "user_verifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "PENDING",
                "VERIFIED",
                "FAILED",
                name="userverificationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "id_document_type",
            sa.Enum(
                "ID_CARD",
                "NIN",
                "DRIVERS_LICENSE",
                "PASSPORT",
                name="userverificationiddocumenttype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id_document_image_url", sa.String(length=500), nullable=True),
        sa.Column(
            "id_document_image_cloudinary_public_id",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column("face_capture_image_url", sa.String(length=500), nullable=True),
        sa.Column(
            "face_capture_image_cloudinary_public_id",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("provider_reference", sa.String(length=255), nullable=False),
        sa.Column("provider_payload_json", sa.JSON(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column(
            "available_balance", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column("pending_balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "favorite_sellers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "seller_id", name="uq_favorite_sellers_user_seller"
        ),
    )
    op.create_index(
        "idx_fav_sellers_user_created",
        "favorite_sellers",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "hustle_lists",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("buyer_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "OPEN",
                "ACCEPTED",
                "CONVERTED",
                "CANCELLED",
                "EXPIRED",
                name="hustleliststatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("shopping_location_id", sa.Uuid(), nullable=True),
        sa.Column("delivery_address_id", sa.Uuid(), nullable=True),
        sa.Column("delivery_fee", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("delivery_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_window_label", sa.String(length=120), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["delivery_address_id"], ["addresses.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["shopping_location_id"],
            ["service_area_locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payout_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column("payout_account_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "PAID",
                "FAILED",
                name="payoutrequeststatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("provider_reference", sa.String(length=255), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payout_account_id"],
            ["payout_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "unique_pending_processing_payout_per_seller",
        "payout_requests",
        ["seller_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'processing')"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=280), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("unit_label", sa.String(length=50), nullable=False),
        sa.Column("base_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("low_stock_threshold", sa.Integer(), nullable=False),
        sa.Column(
            "stock_status",
            sa.Enum(
                "IN_STOCK",
                "LOW_STOCK",
                "OUT_OF_STOCK",
                name="productstockstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "publish_status",
            sa.Enum(
                "DRAFT",
                "PUBLISHED",
                "ARCHIVED",
                name="productpublishstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "availability_status",
            sa.Enum(
                "AVAILABLE",
                "HIDDEN",
                name="productavailabilitystatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("shelf_life_text", sa.String(length=255), nullable=False),
        sa.Column("view_count_cached", sa.Integer(), nullable=False),
        sa.Column("order_count_cached", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seller_id", "slug", name="uq_products_seller_slug"),
    )
    op.create_table(
        "sale_campaigns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "campaign_type",
            sa.Enum(
                "SINGLE_ITEM", "STORE_WIDE", name="salecampaigntype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "ACTIVE",
                "ENDED",
                "CANCELLED",
                name="salecampaignstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "seller_daily_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("orders_count", sa.Integer(), nullable=False),
        sa.Column("completed_orders_count", sa.Integer(), nullable=False),
        sa.Column("earnings_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("avg_rating", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("avg_delivery_minutes", sa.Integer(), nullable=False),
        sa.Column("success_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "seller_id", "metric_date", name="uq_seller_daily_metrics_seller_date"
        ),
    )
    op.create_index(
        "idx_seller_daily_metrics_date",
        "seller_daily_metrics",
        ["metric_date"],
        unique=False,
    )
    op.create_table(
        "seller_presence",
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OFFLINE",
                "ACTIVE",
                "AT_MARKET",
                "BUSY",
                name="sellerpresencestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("current_location_id", sa.Uuid(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["current_location_id"],
            ["service_area_locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("seller_id"),
    )
    op.create_table(
        "seller_service_areas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["service_area_locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "seller_id", "location_id", name="uq_seller_service_areas_seller_loc"
        ),
    )
    op.create_table(
        "seller_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seller_id", "tag_id", name="uq_seller_tags_seller_tag"),
    )
    op.create_table(
        "cart_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cart_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_label_snapshot", sa.String(length=50), nullable=False),
        sa.Column("product_name_snapshot", sa.String(length=255), nullable=False),
        sa.Column(
            "unit_price_snapshot", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "discount_price_snapshot", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "line_total_snapshot", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "snapshotted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["carts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cart_id", "product_id", name="uq_cart_items_cart_product"),
    )
    op.create_table(
        "favorite_products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "product_id", name="uq_favorite_products_user_product"
        ),
    )
    op.create_table(
        "hustle_list_dispatches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hustle_list_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "DIRECT",
                "MARKETPLACE",
                name="hustlelistdispatchchannel",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("target_seller_id", sa.Uuid(), nullable=True),
        sa.Column("accepted_by_seller_id", sa.Uuid(), nullable=True),
        sa.Column("buyer_approved_seller_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "BUYER_APPROVAL_PENDING",
                "DECLINED",
                "EXPIRED",
                "WITHDRAWN",
                name="hustlelistdispatchstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (\n                channel = 'marketplace' AND buyer_approved_seller_id IS NOT NULL\n            ) OR (\n                channel = 'direct'\n            )\n            ",
            name="chk_dispatch_buyer_approval",
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_seller_id"],
            ["seller_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["buyer_approved_seller_id"],
            ["seller_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hustle_list_id"],
            ["hustle_lists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_seller_id"],
            ["seller_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hustle_list_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hustle_list_id", sa.Uuid(), nullable=False),
        sa.Column("requested_name", sa.String(length=255), nullable=False),
        sa.Column("quantity_value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit_label", sa.String(length=50), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hustle_list_id"],
            ["hustle_lists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "listing_view_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("viewer_user_id", sa.Uuid(), nullable=True),
        sa.Column("seller_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("source_screen", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["viewer_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_lve_product_created",
        "listing_view_events",
        ["product_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_lve_seller_created",
        "listing_view_events",
        ["seller_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_lve_viewer_created",
        "listing_view_events",
        ["viewer_user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_number", sa.String(length=32), nullable=False),
        sa.Column("buyer_id", sa.Uuid(), nullable=False),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "CATALOG_CHECKOUT",
                "HUSTLE_LIST",
                name="ordersourcetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_cart_id", sa.Uuid(), nullable=True),
        sa.Column("source_hustle_list_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_PAYMENT",
                "ACCEPTED",
                "SHOPPING",
                "DELIVERING",
                "REVIEWING",
                "DONE",
                "CANCELLED",
                "DISPUTED",
                name="orderstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("pickup_location_id", sa.Uuid(), nullable=True),
        sa.Column("delivery_address_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("subtotal_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "delivery_fee_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "service_fee_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("seller_eta_minutes", sa.Integer(), nullable=True),
        sa.Column("special_instructions", sa.Text(), nullable=False),
        sa.Column(
            "seller_marked_delivered_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "buyer_confirmed_delivered_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (\n                source_type = 'catalog_checkout'\n                AND source_cart_id IS NOT NULL\n                AND source_hustle_list_id IS NULL\n            ) OR (\n                source_type = 'hustle_list'\n                AND source_hustle_list_id IS NOT NULL\n                AND source_cart_id IS NULL\n            )\n            ",
            name="chk_order_source_consistency",
        ),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pickup_location_id"],
            ["service_area_locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_cart_id"],
            ["carts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_hustle_list_id"],
            ["hustle_lists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_number"),
    )
    op.create_table(
        "product_categories",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("product_id", "category_id"),
    )
    op.create_table(
        "product_daily_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("orders_count", sa.Integer(), nullable=False),
        sa.Column(
            "gross_sales_amount", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id", "metric_date", name="uq_product_daily_metrics_product_date"
        ),
    )
    op.create_index(
        "idx_product_daily_metrics_date",
        "product_daily_metrics",
        ["metric_date"],
        unique=False,
    )
    op.create_table(
        "product_images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("image_file_url", sa.String(length=500), nullable=False),
        sa.Column("cloudinary_public_id", sa.String(length=255), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "tag_id", name="uq_product_tags_product_tag"),
    )
    op.create_table(
        "sale_campaign_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "original_price_snapshot", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "discounted_price", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["sale_campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "campaign_id", "product_id", name="uq_sale_campaign_items_campaign_product"
        ),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "conversation_type",
            sa.Enum("DIRECT", "ORDER", name="conversationtype", native_enum=False),
            nullable=False,
        ),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "RESOLVED", name="conversationstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("last_message_id", sa.Uuid(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_preview", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_conv_status_lastmsg",
        "conversations",
        ["status", "last_message_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_last_message_id"),
        "conversations",
        ["last_message_id"],
        unique=False,
    )
    op.create_table(
        "order_complaints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "REVIEWING",
                "REVIEWED",
                "RESOLVED",
                "DISMISSED",
                name="ordercomplaintstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("resolution_note", sa.Text(), nullable=False),
        sa.Column("resolved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("source_hustle_list_item_id", sa.Uuid(), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit_label", sa.String(length=50), nullable=False),
        sa.Column("base_unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "final_unit_price", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("line_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "fulfillment_status",
            sa.Enum(
                "PENDING",
                "BOUGHT",
                "SUBSTITUTED",
                "CANCELLED",
                "DELIVERED",
                name="orderitemfulfillmentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("image_snapshot", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_hustle_list_item_id"],
            ["hustle_list_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "rating IS NULL OR (rating >= 1 AND rating <= 5)",
            name="chk_order_review_rating_range",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "order_status_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_PAYMENT",
                "ACCEPTED",
                "SHOPPING",
                "DELIVERING",
                "REVIEWING",
                "DONE",
                "CANCELLED",
                "DISPUTED",
                name="orderstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("payer_user_id", sa.Uuid(), nullable=False),
        sa.Column("saved_payment_method_id", sa.Uuid(), nullable=True),
        sa.Column("payment_method", sa.String(length=50), nullable=False),
        sa.Column("provider_reference", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "INITIATED",
                "PENDING",
                "SUCCEEDED",
                "FAILED",
                "REFUNDED",
                name="paymentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payer_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["saved_payment_method_id"],
            ["saved_payment_methods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "unique_succeeded_payment_per_order",
        "payments",
        ["order_id"],
        unique=True,
        postgresql_where=sa.text("order_id IS NOT NULL AND status = 'succeeded'"),
    )
    op.create_table(
        "wallet_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "FUNDING",
                "PAYMENT",
                "REFUND",
                "PAYOUT",
                "EARNING",
                "FEE",
                name="wallettransactiontype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("payout_request_id", sa.Uuid(), nullable=True),
        sa.Column("provider_reference", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCEEDED",
                "FAILED",
                name="wallettransactionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (\n                order_id IS NOT NULL AND payout_request_id IS NULL\n            ) OR (\n                order_id IS NULL AND payout_request_id IS NOT NULL\n            ) OR (\n                order_id IS NULL AND payout_request_id IS NULL\n            )\n            ",
            name="chk_wallet_txn_single_reference",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payout_request_id"],
            ["payout_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("sender_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "message_type",
            sa.Enum("TEXT", "SYSTEM", name="messagetype", native_enum=False),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_msg_conv_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "order_complaint_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_complaint_id", sa.Uuid(), nullable=False),
        sa.Column("complaint_tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["complaint_tag_id"],
            ["complaint_tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_complaint_id"],
            ["order_complaints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_complaint_id",
            "complaint_tag_id",
            name="uq_order_complaint_tags_complaint_tag",
        ),
    )
    op.create_table(
        "order_item_adjustments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_item_id", sa.Uuid(), nullable=False),
        sa.Column("proposed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("old_unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("new_unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                name="orderitemadjustmentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_item_alternatives",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_item_id", sa.Uuid(), nullable=False),
        sa.Column("suggested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("suggested_product_id", sa.Uuid(), nullable=True),
        sa.Column("suggested_name", sa.String(length=255), nullable=False),
        sa.Column("suggested_unit_label", sa.String(length=50), nullable=False),
        sa.Column("suggested_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                name="orderitemalternativestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suggested_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suggested_product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_review_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_review_id", sa.Uuid(), nullable=False),
        sa.Column("review_tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_review_id"],
            ["order_reviews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_tag_id"],
            ["review_tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_review_id", "review_tag_id", name="uq_order_review_tags_review_tag"
        ),
    )
    op.create_table(
        "user_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reporter_user_id", sa.Uuid(), nullable=False),
        sa.Column("reported_user_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("reason_type", sa.String(length=100), nullable=False),
        sa.Column("details", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "REVIEWED",
                "RESOLVED",
                "DISMISSED",
                name="userreportstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("resolution_note", sa.Text(), nullable=False),
        sa.Column("resolved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reported_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_urep_conversation", "user_reports", ["conversation_id"], unique=False
    )
    op.create_index(
        "idx_urep_reporter_created",
        "user_reports",
        ["reporter_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_urep_status_created",
        "user_reports",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "conversation_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("last_read_message_id", sa.Uuid(), nullable=True),
        sa.Column("unread_count_cached", sa.Integer(), nullable=False),
        sa.Column("muted_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_read_message_id"], ["messages.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id", "user_id", name="uq_conversation_members_conv_user"
        ),
    )
    op.create_index(
        "idx_conv_members_conversation",
        "conversation_members",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        "idx_conv_members_user_joined",
        "conversation_members",
        ["user_id", "joined_at"],
        unique=False,
    )
    op.create_table(
        "message_attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column("cloudinary_public_id", sa.String(length=255), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_attachments")
    op.drop_index("idx_conv_members_user_joined", table_name="conversation_members")
    op.drop_index("idx_conv_members_conversation", table_name="conversation_members")
    op.drop_table("conversation_members")
    op.drop_index("idx_urep_status_created", table_name="user_reports")
    op.drop_index("idx_urep_reporter_created", table_name="user_reports")
    op.drop_index("idx_urep_conversation", table_name="user_reports")
    op.drop_table("user_reports")
    op.drop_table("order_review_tags")
    op.drop_table("order_item_alternatives")
    op.drop_table("order_item_adjustments")
    op.drop_table("order_complaint_tags")
    op.drop_index("idx_msg_conv_created", table_name="messages")
    op.drop_table("messages")
    op.drop_table("wallet_transactions")
    op.drop_index(
        "unique_succeeded_payment_per_order",
        table_name="payments",
        postgresql_where=sa.text("order_id IS NOT NULL AND status = 'succeeded'"),
    )
    op.drop_table("payments")
    op.drop_table("order_status_events")
    op.drop_table("order_reviews")
    op.drop_table("order_items")
    op.drop_table("order_complaints")
    op.drop_index(op.f("ix_conversations_last_message_id"), table_name="conversations")
    op.drop_index("idx_conv_status_lastmsg", table_name="conversations")
    op.drop_table("conversations")
    op.drop_table("sale_campaign_items")
    op.drop_table("product_tags")
    op.drop_table("product_images")
    op.drop_index("idx_product_daily_metrics_date", table_name="product_daily_metrics")
    op.drop_table("product_daily_metrics")
    op.drop_table("product_categories")
    op.drop_table("orders")
    op.drop_index("idx_lve_viewer_created", table_name="listing_view_events")
    op.drop_index("idx_lve_seller_created", table_name="listing_view_events")
    op.drop_index("idx_lve_product_created", table_name="listing_view_events")
    op.drop_table("listing_view_events")
    op.drop_table("hustle_list_items")
    op.drop_table("hustle_list_dispatches")
    op.drop_table("favorite_products")
    op.drop_table("cart_items")
    op.drop_table("seller_tags")
    op.drop_table("seller_service_areas")
    op.drop_table("seller_presence")
    op.drop_index("idx_seller_daily_metrics_date", table_name="seller_daily_metrics")
    op.drop_table("seller_daily_metrics")
    op.drop_table("sale_campaigns")
    op.drop_table("products")
    op.drop_index(
        "unique_pending_processing_payout_per_seller",
        table_name="payout_requests",
        postgresql_where=sa.text("status IN ('pending', 'processing')"),
    )
    op.drop_table("payout_requests")
    op.drop_table("hustle_lists")
    op.drop_index("idx_fav_sellers_user_created", table_name="favorite_sellers")
    op.drop_table("favorite_sellers")
    op.drop_table("wallets")
    op.drop_table("user_verifications")
    op.drop_index("idx_user_blocks_blocker", table_name="user_blocks")
    op.drop_table("user_blocks")
    op.drop_table("seller_profiles")
    op.drop_index(
        "unique_default_payment_method_per_user",
        table_name="saved_payment_methods",
        postgresql_where=sa.text("is_default"),
    )
    op.drop_table("saved_payment_methods")
    op.drop_table("refresh_token_blacklist")
    op.drop_index(
        "unique_default_payout_account_per_user",
        table_name="payout_accounts",
        postgresql_where=sa.text("is_default"),
    )
    op.drop_table("payout_accounts")
    op.drop_table("password_reset_otps")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        "idx_location_daily_metrics_date", table_name="location_daily_metrics"
    )
    op.drop_table("location_daily_metrics")
    op.drop_table("email_verification_otps")
    op.drop_index("ix_device_reg_user_device", table_name="device_registrations")
    op.drop_table("device_registrations")
    op.drop_index("idx_carts_buyer_status_updated", table_name="carts")
    op.drop_table("carts")
    op.drop_index(
        "uq_one_default_address_per_user",
        table_name="addresses",
        postgresql_where=sa.text("is_default"),
    )
    op.drop_table("addresses")
    op.drop_table("users")
    op.drop_table("tags")
    op.drop_table("service_area_locations")
    op.drop_table("review_tags")
    op.drop_table("complaint_tags")
    op.drop_index("idx_categories_active_order", table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
